# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Differing < Formula
  desc "A stand-alone code review tool for reviewing LLM-generated changes"
  homepage "https://github.com/philz/differing"
  version "0.0.23"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/philz/differing/releases/download/v0.0.23/differing_darwin_amd64"
      sha256 "6600351e1f0f94854f6ceafe4f6e7cf147297d15f7d736cdf470b552f66a8b72"

      def install
        bin.install "differing"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/philz/differing/releases/download/v0.0.23/differing_darwin_arm64"
      sha256 "a1c49f8cd04c3bd1a650c75f572cbda33a4f2e9c14993e35794aa8e728b5c87a"

      def install
        bin.install "differing"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/philz/differing/releases/download/v0.0.23/differing_linux_amd64"
      sha256 "9c22d437fdcab2605e459a86ad1785d388bc7118c946ee4235b2535de647a9b9"
      def install
        bin.install "differing"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/philz/differing/releases/download/v0.0.23/differing_linux_arm64"
      sha256 "4e74657dfa6c1dfe29cf4ba8cfd7bd65aee2f905ec4881b7411f61dcf362a1e6"
      def install
        bin.install "differing"
      end
    end
  end

  test do
    system "#{bin}/differing", "--help"
  end
end
